### ISSUE TITLE
#US10 Como usuario quiero tener una forma de contactar a la Biblioteca para hacer consultas

### ISSUE THREAD

**Issue by carlos-linero** [proyectos-tsdwad/integrador-modulo-fullstack#12]
- [ ] #TK29 Definir método de contacto.
- [x] #TK30 Diseñar vista.
- [ ] #TK31 Maquetar la misma.
- [ ] #TK32 Testear.

**Comment by carlariossuarez** [comment]
Vista de página de contacto. Link a figma: [Figma](https://www.figma.com/file/AkOD1vuaVk4IBh6NEYdsod/Biblioteca?node-id=0%3A1)

![image](https://user-images.githubusercontent.com/91499396/193703927-2813d34a-28b6-4cdf-a7c3-2451b3f217a5.png)
