### ISSUE TITLE
#US11 Como usuario quiero ver el form del registro de cuenta

### ISSUE THREAD

**Issue by carlos-linero** [proyectos-tsdwad/integrador-modulo-fullstack#13]
- [x] #TK34 Diseñar registro.
- [x] #TK35 Implementar lógica de registro del lado del cliente.
- [ ] #TK36 Emitir mensaje “Usuario registrado con éxito” cuando se complete el registro.

**Comment by carlariossuarez** [comment]
Vista de formulario registro. Link a figma: [Figma](https://www.figma.com/file/AkOD1vuaVk4IBh6NEYdsod/Biblioteca?node-id=0%3A1)

![image](https://user-images.githubusercontent.com/91499396/193703765-09c78e48-05e5-4f9f-aad0-ab0654d3a180.png)
