### ISSUE TITLE
#13 Como usuario quiero ver mi información personal de la cuenta      

### ISSUE THREAD

**Issue by carlos-linero** [proyectos-tsdwad/integrador-modulo-fullstack#15]
- [x] #TK42 Diseño de vista de perfil.
- [x] #TK43 Maquetado del diseño.
- [ ] #TK44 Testear funcionalidad.

**Comment by carlariossuarez** [comment]
Vista de información personal. Link a figma: [Figma](https://www.figma.com/file/AkOD1vuaVk4IBh6NEYdsod/Biblioteca?node-id=76%3A113)

![image](https://user-images.githubusercontent.com/91499396/193703367-9732c8b8-a0ca-46ad-b74b-d2a4952d6085.png)
