### ISSUE TITLE
#US14 Como usuario registrado quiero poder ver mi historial de actividades dentro de mi perfil

### ISSUE THREAD

**Issue by carlos-linero** [proyectos-tsdwad/integrador-modulo-fullstack#16]
- [x] #15 
- [ ] #TK46 Diseño de vista de historial de actividades.
- [ ] #TK47 Maquetado la misma.
- [ ] #TK48 Testear funcionalidad.

**Comment by carlariossuarez** [comment]
Vista de historial de actividades. Link de figma: [Figma](https://www.figma.com/file/AkOD1vuaVk4IBh6NEYdsod/Biblioteca?node-id=76%3A113)

![image](https://user-images.githubusercontent.com/91499396/193702480-89546304-9c2f-46b0-80c8-698676141c33.png)
