### ISSUE TITLE
#US02 Como usuario quiero poder ver el header del home

### ISSUE THREAD

**Issue by carlos-linero** [proyectos-tsdwad/integrador-modulo-fullstack#2]
- [x] 	#TK05 Diseñar header del home.
- [x] 	#TK06 Maquetar el mismo.
- [x] #TK07 Testear.

**Comment by carlariossuarez** [comment]
Vista de header. Link a figma: [Figma](https://www.figma.com/file/AkOD1vuaVk4IBh6NEYdsod/Biblioteca?node-id=0%3A1)

![image](https://user-images.githubusercontent.com/91499396/193705321-cd888408-7bfe-4050-a2e1-af0bb020a67d.png)
