### ISSUE TITLE
#US01 Como usuario quiero poder navegar entre las distintas secciones de la pagina 

### ISSUE THREAD

**Issue by carlos-linero** [proyectos-tsdwad/integrador-modulo-fullstack#3]
- [x]   #TK01 Definir y diseñar menú.
- [x] 	#TK02 Maquetar menú.
- [x] 	#TK03 Enlazar las diferentes secciones de la página al menú.
- [x]  #TK04 Testear funcionalidad.

**Comment by carlariossuarez** [comment]
Vista de navbar. Link a figma: [Figma](https://www.figma.com/file/AkOD1vuaVk4IBh6NEYdsod/Biblioteca?node-id=0%3A1)

![image](https://user-images.githubusercontent.com/91499396/193705233-16abcc93-6d18-41bd-bf0e-eb65a3fffae9.png)
