### ISSUE TITLE
#US25 Como usuario quiero poder crear una cuenta usando el form de registro (simulación)

### ISSUE THREAD

**Issue by carlos-linero** [proyectos-tsdwad/integrador-modulo-fullstack#54]
- [x] Definir el alcance y tecnologías para el mismo.
- [x] Codificar simulación.
- [x] Validar con expresiones regulares - #52 .
- [x] Testear.

**Comment by Jesica-A** [comment]
### Alcance y tecnología:
Se podría hacer con **PHP** y **MySQL** instalando **xampp**. 
Instalado xampp, ir a la carpeta _thdocs_ y tener nuestro proyecto ahí de **forma local por el momento** (usamos **localhost/**...)

**Comment by Jesica-A** [comment]
### Modificaciones:
Los inputs del form realizado no coinciden con la tabla "user" de nuestra base de datos. 
Adjunto fotos de como estaba hecho al principio:

![Image](https://user-images.githubusercontent.com/69865928/198654191-031deb53-dd4a-4c94-af18-13ec908773a0.png)

![Image](https://user-images.githubusercontent.com/69865928/198654442-d2e9509b-da7a-4a39-84eb-2ac1220aa025.png)

Se cambiaron todas las extensiones **.html** por **.php** y se agrego un archivo **database.php**


![Image](https://user-images.githubusercontent.com/69865928/198671911-c9fa52e9-7cd1-4bee-9767-e0bdc630ae38.png)



### Actual:
Adjunto fotos de las moficaciones que se realizaron:

![Image](https://user-images.githubusercontent.com/69865928/198655298-4a2ea1fe-4582-4980-b84a-0cdfe080205f.png)

![Image](https://user-images.githubusercontent.com/69865928/198659766-4254220a-43c6-4e30-9bbb-1db3bc0d81be.png)


### Script:
Adjunto [la base que hice](https://drive.google.com/file/d/1RjE60WUHjQztSBVHllf0pj2EW1jSkNX2/view?usp=sharing), solo tiene la tabla "user". A medida que se hagan mas cosas se van agregando las demas tablas y relaciones en base los archivos en la carpeta [documentacion ](https://github.com/proyectos-tsdwad/integrador-modulo-fullstack/tree/main/documentation/data%20base) del repositorio actual.



### Resultado:

![Image](https://user-images.githubusercontent.com/69865928/198669968-60a1c0ed-db6a-4fce-b178-d096b01f5a1b.png)

Cuando completamos el form se cargan correctamente los datos en la base:

![Image](https://user-images.githubusercontent.com/69865928/198670162-e5cb58f7-d1e3-4816-92c2-388d3fb44d9e.png)
