### ISSUE TITLE
#US03 Como usuario quiero poder ver debajo del header info destacada

### ISSUE THREAD

**Issue by carlos-linero** [proyectos-tsdwad/integrador-modulo-fullstack#6]
- [x] 	#TK08 Diseñar anexo debajo del header que contenga dicha info.
- [ ] 	#TK09 Maquetar el mismo.
- [ ] #TK10 Testear.

**Comment by carlariossuarez** [comment]
Vista info destacada en header. Link a figma: [Figma](https://www.figma.com/file/AkOD1vuaVk4IBh6NEYdsod/Biblioteca?node-id=0%3A1)

![image](https://user-images.githubusercontent.com/91499396/193705117-30937ae4-80dd-4193-8fba-9c3641ab04da.png)
