### ISSUE TITLE
#US05 Como usuario quiero poder ver el detalle de un libro y poder reservarlo 

### ISSUE THREAD

**Issue by carlos-linero** [proyectos-tsdwad/integrador-modulo-fullstack#8]
- [x] #7 
- [x] #TK14 Diseño de vista.
- [x] #TK15 Maquetado del mismo.
- [x] #TK16 Testear funcionalidad.

**Comment by carlariossuarez** [comment]
Vista de detalle de libro. Link a figma: [Figma](https://www.figma.com/file/AkOD1vuaVk4IBh6NEYdsod/Biblioteca?node-id=0%3A1)

![image](https://user-images.githubusercontent.com/91499396/193704789-578b4596-1944-4742-80c4-5a9b4cf5e690.png)
